export const GET_CITIES = 'GET_CITIES'
export const GET_CITY_BY_ID = 'GET_CITY_BY_ID'

export const GET_ITINERARIES_BY_CITY = 'GET_ITINERARIES_BY_CITY'

export const LOADING = 'LOADING'

export const GET_ACTIVITIES_BY_ITINERARY_ID = 'GET_ACTIVITIES_BY_ITINERARY_ID'
